project:
  type: website

website:
  title: INFO 523 | BMW Price Prediction
  navbar:
    right:
    - icon: github
      href: https://github.com/INFO523-Fall25-101-201/final-project-min-set-khant-solo
    - text: Live Site
      href: https://minsetkhant.quarto.pub/info-523--bmw-price-prediction/
        
    left:
      - text: Project Home
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: Final_Presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
